### ISSUE TITLE
how to test this MPC?

### ISSUE THREAD

**Issue by chan-yuu** [TorBorve/mpc_local_planner#10]
![image](https://github.com/user-attachments/assets/f0fdbd54-fed1-4fb9-b8b4-94bf38fc57df)
I'm using the noetic version, how do I give him the data?
![image](https://github.com/user-attachments/assets/e68784d3-a5eb-481f-a7b7-b5212fccc3b6)

**Comment by chan-yuu** [comment]
![image](https://github.com/user-attachments/assets/5c42b02c-41c1-4864-af33-6986bf76f2a2)
oh, why the local path is like this? so flat

**Comment by chan-yuu** [comment]
In other words, What does your profile "sim.yaml" say?
It's mine:

mode: "path_tracking"  # 模式：路径跟踪

loop_Hz: 50  # 运行频率，单位为赫兹
loop_HZ: 50  # 运行频率，单位为赫兹

twist_topic: "/twist"  # 线速度和角速度发布话题

stop_topic: "/stop"  # 紧急停车发布话题

# actual_steering_topic: "/actual_steering_angle"  # 当前方向盘角度发布话题
actual_steering_topic: "/steering_state"  # 当前方向盘角度发布话题

steering_topic: "/steering_cmd"  # 期望方向盘角度发布话题

throttle_topic: "/throttle_cmd"  # 油门控制发布话题

parking_topic: "/move_base_simple/goal"  # 停车位的位姿话题

path_topic: "/path"  # 全局路径发布话题

# map_frame: "odom"  # 全局参考坐标系
map_frame: "world"  # 全局参考坐标系

car_frame: "base_footprint"  # 汽车的参考坐标系

mpc_N: 10  # MPC预测步数

nlp_solver_type: "SQP_RTI"  # SQP或SQP_RTI

mpc_dt: 0.35  # MPC步时间间隔

path_tracking_vel: 3.0  # 路径跟踪速度

parking_vel: 1.0  # 停车速度

throttle_min: 0  # 油门最小值

throttle_max: 1.0  # 油门最大值

throttle_dot_max: 0.33  # 每秒最大油门变化率

max_steering_angle: 0.57  # 最大转向角度（弧度）

max_steering_rotation_speed: 0.8  # 最大车轮旋转速度（弧度/秒）

wheelbase: 2.65  # 轴距

radius: 0.225  # 车轮半径

gear_ratio: 0.05  # 齿轮比

mass_car: 70  # 车辆质量

voltage: 48  # 电池电压

drag_coefficient: 0.218  # 空气阻力系数

frontal_area: 1  # 车辆正面面积

rolling_resistance: 0.015  # 滚动阻力系数

steering_ratio: 17.3  # 转向比率

![image](https://github.com/user-attachments/assets/38f4c157-f3b7-43a0-a0c2-680d8a93bfc5)

seems better

**Comment by chan-yuu** [comment]
![image](https://github.com/user-attachments/assets/3e7756c8-6ae9-4574-8de6-65620bab073d)
Sometimes they don't coincide.

**Comment by chan-yuu** [comment]
![image](https://github.com/user-attachments/assets/f705f9bd-df24-499b-acc6-a3729a431536)
so why?

**Comment by TorBorve** [comment]
Hi,

Which branch/commit are you on?

I am not sure why the interpolated path ends up beeing linear in some of the picture you showed. If I am not mistaken the order was changed to first order in a certain commit because that gave better performance in a certain scenario I experienced.

**Comment by chan-yuu** [comment]
archive-sem23 for noetic

**Comment by TorBorve** [comment]
This is the version I was talking about that has linear interpolation. If you want a third order interpolation instead then:

Comment out/remove:

```
#If you want linear poly fit.
add_compile_definitions(LINEAR_POLY_FIT)
```
from CMakeLists.txt. And recompile the MPC.

**Comment by chan-yuu** [comment]
Thanks a lot. It worked.
![2024-09-07 00-58-38 的屏幕截图](https://github.com/user-attachments/assets/3cfc732b-3f78-4142-9ed6-1912af304884)
What is the "/actual steering angle" parameter used for? Does the current Angle need to be fed back in the simulation?

# actual_steering_topic: "/actual_steering_angle"  

actual_steering_topic: "/steering_state" 

steering_topic: "/steering_cmd" 

throttle_topic: "/throttle_cmd"

**Comment by TorBorve** [comment]
Yes. "actual_steering_topic" is a topic where the current steering angle is published. The MPC gives out an steering angle command, however it might be that the servo system or similar is not able to track this signal. Thus the actual steering angle might be different from the one you commanded. If you don't have this signal available the i suggest that you edit RosMPC.cpp solve function in the following way:

```
static double prevSteeringCmd = 0; // NEW LINE

...
State state{tfCar.transform.translation.x,
                tfCar.transform.translation.y,
                util::getYaw(tfCar.transform.rotation),
                currentVel_,
                augmentedStates[0],
                prevSteeringCmd, // EDITED LINE
                prevThrottle}; // the value of gamma is computed in PathTrackingSys.cpp
...
steeringPub_.publish(msg);
prevSteeringCmd = msg.data / steeringRatio_; // NEW LINE
```
This is the same as what is done with the ThrottleCmd. Then you can just publish zero to the /actual_steering_angle topic. However, if you are doing this then you need to ensure that the "max_steering_rotation_speed" parameter is not higher than what the steering system is able to follow. If you use the sim.yaml is should be fine.

**Comment by chan-yuu** [comment]
I see, thank you.
