### ISSUE TITLE
How to post Twist topic on a real car?

### ISSUE THREAD

**Issue by chan-yuu** [TorBorve/mpc_local_planner#12]
It's data structure is:
```
Header header
  uint32 seq
  time stamp
  string frame_id
Twist twist
  Vector3 linear
    float64 x
    float64 y
    float64 z
  Vector3 angular
    float64 x
    float64 y
    float64 z
```
I want to know how to calculate and publish Angular data. I think the twist here should be for vertical control. So, are we actually not using Angular?

**Comment by TorBorve** [comment]
For the mpc the only thing the twist is used for is to get the velocity of the car. It does this by taking the length of the "linear" vector. 

If you just publish a twist message with this information then it should work.
