### ISSUE TITLE
Where is the part about building the cost function and what kind of cost function is designed?

### ISSUE THREAD

**Issue by chan-yuu** [TorBorve/mpc_local_planner#13]
As shown in the title. Looking forward to your answer.

**Comment by TorBorve** [comment]
Hi,

See lines 123-127 in acados/mpcPathTracking.py

The mpc uses a least-squares cost function of several states and functions like the distance to the path (cross track error), angle relative to the path, control effort used and more.  See the costFunc function in the script for more details.

You can tune the cost function by changing W in line 127 (".cost.W").

**Comment by chan-yuu** [comment]
thanks
